services:
  postgres:
    image: postgres:latest
    container_name: nest-test-task
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: